package mikrotik

import (
	"strings"
	"testing"

	"github.com/irhabi89/mikhmon/internal/domain/dto"
)

// TestOnLoginGenerator_Parse verifies that Parse correctly extracts metadata
// from a script generated by Generate. This is the critical round-trip test.
func TestOnLoginGenerator_Parse(t *testing.T) {
	g := NewOnLoginGenerator()

	tests := []struct {
		name string
		req  *dto.ProfileRequest
	}{
		{
			name: "ntf mode with lock user",
			req: &dto.ProfileRequest{
				Name:         "Basic",
				ExpireMode:   "ntf",
				Validity:     "7d",
				Price:        2000,
				SellingPrice: 2500,
				LockUser:     "Enable",
				LockServer:   "Disable",
			},
		},
		{
			name: "remc mode with lock user and server",
			req: &dto.ProfileRequest{
				Name:         "Premium",
				ExpireMode:   "remc",
				Validity:     "30d",
				Price:        5000,
				SellingPrice: 5500,
				LockUser:     "Enable",
				LockServer:   "Enable",
			},
		},
		{
			name: "rem mode no lock",
			req: &dto.ProfileRequest{
				Name:         "Daily",
				ExpireMode:   "rem",
				Validity:     "1d",
				Price:        1000,
				SellingPrice: 1200,
				LockUser:     "Disable",
				LockServer:   "Disable",
			},
		},
		{
			name: "mode 0 no expire",
			req: &dto.ProfileRequest{
				Name:         "Unlimited",
				ExpireMode:   "0",
				Validity:     "",
				Price:        10000,
				SellingPrice: 12000,
				LockUser:     "Disable",
				LockServer:   "Disable",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			script := g.Generate(tt.req)
			if script == "" {
				t.Fatal("Generate returned empty script")
			}

			parsed := g.Parse(script)
			if parsed == nil {
				t.Fatal("Parse returned nil")
			}

			// For mode=remc, parse returns "ntfc" if /system script add found
			// For mode=ntfc, parse returns "ntfc"
			// We only check round-trip for non-compound modes here
			expectedMode := tt.req.ExpireMode
			if tt.req.ExpireMode == "0" {
				// mode "0" produces no :put header, parsing will return empty struct
				// Just verify Generate doesn't panic and returns empty/lock-only script
				return
			}

			if parsed.ExpireMode != expectedMode {
				t.Errorf("ExpireMode: got %q, want %q", parsed.ExpireMode, expectedMode)
			}
			if parsed.Price != tt.req.Price {
				t.Errorf("Price: got %.0f, want %.0f", parsed.Price, tt.req.Price)
			}
			if parsed.Validity != tt.req.Validity {
				t.Errorf("Validity: got %q, want %q", parsed.Validity, tt.req.Validity)
			}
			if parsed.SellingPrice != tt.req.SellingPrice {
				t.Errorf("SellingPrice: got %.0f, want %.0f", parsed.SellingPrice, tt.req.SellingPrice)
			}
			if parsed.LockUser != tt.req.LockUser {
				t.Errorf("LockUser: got %q, want %q", parsed.LockUser, tt.req.LockUser)
			}
			if parsed.LockServer != tt.req.LockServer {
				t.Errorf("LockServer: got %q, want %q", parsed.LockServer, tt.req.LockServer)
			}
		})
	}
}

// TestOnLoginGenerator_Generate_ContainsPicIndex verifies the script uses correct index [:pic $exp 7 15]
// (not 16), matching MIKHMON PHP original.
func TestOnLoginGenerator_Generate_ContainsPicIndex(t *testing.T) {
	g := NewOnLoginGenerator()
	req := &dto.ProfileRequest{
		Name:         "Test",
		ExpireMode:   "ntf",
		Validity:     "7d",
		Price:        1000,
		SellingPrice: 1200,
		LockUser:     "Disable",
		LockServer:   "Disable",
	}
	script := g.Generate(req)

	// Should contain [:pic $exp 7 15] (NOT 16)
	if !strings.Contains(script, "[:pic $exp 7 15]") {
		t.Errorf("Script should contain '[:pic $exp 7 15]', got:\n%s", script)
	}
	if strings.Contains(script, "[:pic $exp 7 16]") {
		t.Errorf("Script should NOT contain '[:pic $exp 7 16]', got:\n%s", script)
	}
}

// TestOnLoginGenerator_Generate_ExpirationBlock verifies closing brace structure.
func TestOnLoginGenerator_Generate_ExpirationBlock(t *testing.T) {
	g := NewOnLoginGenerator()
	req := &dto.ProfileRequest{
		Name:         "Test",
		ExpireMode:   "rem",
		Validity:     "1d",
		Price:        1000,
		SellingPrice: 1200,
		LockUser:     "Disable",
		LockServer:   "Disable",
	}
	script := g.Generate(req)

	// Basic sanity: script starts with :put and ends with }
	if !strings.HasPrefix(script, ":put") {
		t.Errorf("Script should start with ':put', got: %q", script[:min(50, len(script))])
	}
	if !strings.HasSuffix(script, "}") {
		t.Errorf("Script should end with '}', got suffix: %q", script[max(0, len(script)-10):])
	}
}

// TestOnLoginGenerator_Mode0_WithLock verifies mode "0" with LockUser produces closing brace.
func TestOnLoginGenerator_Mode0_WithLock(t *testing.T) {
	g := NewOnLoginGenerator()
	req := &dto.ProfileRequest{
		Name:         "Unlimited",
		ExpireMode:   "0",
		Validity:     "",
		Price:        10000,
		SellingPrice: 12000,
		LockUser:     "Enable",
		LockServer:   "Disable",
	}
	script := g.Generate(req)
	// With lock enabled, should end with }
	if !strings.HasSuffix(script, "}") {
		t.Errorf("Mode 0 with LockUser=Enable should end with '}', got: %q", script)
	}
}

// TestOnLoginGenerator_Mode0_NoLock verifies mode "0" without lock produces no footer brace.
func TestOnLoginGenerator_Mode0_NoLock(t *testing.T) {
	g := NewOnLoginGenerator()
	req := &dto.ProfileRequest{
		Name:         "Unlimited",
		ExpireMode:   "0",
		Validity:     "",
		Price:        10000,
		SellingPrice: 12000,
		LockUser:     "Disable",
		LockServer:   "Disable",
	}
	script := g.Generate(req)
	// No expiration, no locks — script may be empty or just the header
	// It should NOT end with }} since that causes syntax error in RouterOS
	if strings.HasSuffix(script, "}}") {
		t.Errorf("Mode 0 with no lock should NOT end with '}}', got: %q", script)
	}
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

func max(a, b int) int {
	if a > b {
		return a
	}
	return b
}
